package com.example.financialplannerapp.data.model

import android.os.Parcelable
import kotlinx.parcelize.Parcelize

@Parcelize
data class UserProfileData(
    val userId: String,
    var name: String? = null,
    var email: String? = null,
    var profilePictureUrl: String? = null,
    var currencyPreference: String? = "USD",
    var notificationPreferences: List<String> = listOf("transactions", "alerts"),
    var lastLogin: Long? = System.currentTimeMillis(),
    var isDataModified: Boolean = false, // Added for UI state tracking
    // Added fields from UserProfileDataFixed to ensure consistency
    var phone: String? = null,
    var dateOfBirth: String? = null, // Format: yyyy-MM-dd
    var occupation: String? = null,
    var monthlyIncome: Double? = null,
    var financialGoals: List<String>? = emptyList(),
    var lastSyncTime: Long? = 0L,
    var createdAt: Long = System.currentTimeMillis(),
    var updatedAt: Long = System.currentTimeMillis()
) : Parcelable

// Keep only one definition of toUserProfileEntity
fun UserProfileData.toUserProfileEntity(): UserProfile {
    return UserProfile(
        id = 0, // Auto-generated by Room
        name = this.name ?: "",
        email = this.email ?: "",
        photoUrl = this.profilePictureUrl,
        currencyPreference = this.currencyPreference,
        notificationEnabled = this.notificationPreferences.isNotEmpty(),
        firebaseUid = this.userId,
        isSyncedWithServer = !this.isDataModified,
        isDataModified = this.isDataModified
    )
}

// Keep only one definition of toUserProfileData
fun UserProfile.toUserProfileData(): UserProfileData {
    return UserProfileData(
        userId = this.firebaseUid ?: "",
        name = this.name,
        email = this.email,
        profilePictureUrl = this.photoUrl,
        currencyPreference = this.currencyPreference,
        notificationPreferences = if (this.notificationEnabled) listOf("transactions", "alerts") else emptyList(),
        lastLogin = System.currentTimeMillis(), // UserProfile doesn't have lastLogin field
        isDataModified = this.isDataModified,
        phone = null, // UserProfile doesn't have these extended fields
        dateOfBirth = null,
        occupation = null,
        monthlyIncome = null,
        financialGoals = emptyList(),
        lastSyncTime = 0L,
        createdAt = System.currentTimeMillis(),
        updatedAt = System.currentTimeMillis()
    )
}